name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.2", "7.3"]
        service: [php-fpm, php-worker]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cp env-example .env
        sed -i -- "s/PHP_VERSION=.*/PHP_VERSION=${{ matrix.php_version }}/g" .env
        docker-compose build ${{ matrix.service }}
